# Generated by Django 5.2 on 2025-04-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='medicacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
