# Generated by Django 5.2 on 2025-05-07 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_paciente_medicacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesion',
            old_name='actividades',
            new_name='notas',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='prioridad',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='evaluación',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='proximasesion',
        ),
        migrations.AddField(
            model_name='paciente',
            name='prioridad_seguimiento',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], default='Media', max_length=20),
        ),
        migrations.AddField(
            model_name='sesion',
            name='seguimiento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='asunto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='terapeuta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
