# Generated by Django 5.2 on 2025-05-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_actividades_sesion_notas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='notas',
        ),
        migrations.AddField(
            model_name='sesion',
            name='actividades',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='duracion',
            field=models.IntegerField(default=30, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='sesion',
            name='estado_emocional',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='proxima_sesion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sesion',
            name='seguimiento_habitos',
            field=models.TextField(blank=True, null=True),
        ),
    ]
